apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-snrk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-snrk@sha256:4f5d0ce6d0a1324e24dd5a93f2b9e6babd8058fd0c7d65df93a7120af2a91906
        name: my-nodejs
        resources: {}
status: {}
